### ISSUE TITLE
gnome-terminal breaks size when creating tabs

### ISSUE THREAD

**Issue by brunobmello25** [pop-os/shell#1048]
**(1) Issue/Bug Description:**
When tiling multiple gnome-terminal windows they will have different vertical sizes depending on whether they have multiple tabs or not

**(2) Steps to reproduce:**

1. setup pop shell to have 2 units of gaps and then enable the tiling feature.
2. tile 4 different gnome-terminals on a 2x2 layout. Let's call the top left "A", the top right "B", the bottom left "C" and the bottom right "D"
3. focus on the terminal A and open another tab with ctrl+shift+T. You will see that it gets a tiny bit smaller vertically, not being fully aligned with the B terminal.
4. focus on the D terminal and open another tab with the same shortcut. You will notice the same problem as mentioned on step 2. Now remove one of the open tabs, you will then see it gets even smaller.

**(3) Expected behavior:**

Terminal windows should keep the same size, respecting gaps and tiling, regardless of whether they have tabs or not.

**(4) Distribution:**

```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
3.36.8

**(6) Pop Shell version:**

```
pop-shell:
  Installed: 1.1.0~1625079016~20.04~9970fd3
  Candidate: 1.1.0~1625079016~20.04~9970fd3
  Version table:
 *** 1.1.0~1625079016~20.04~9970fd3 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Original pop os installation iso

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

one 4k as primary on the left and one full hd as secondary on the right

**(9) Other Installed/Enabled Extensions:**

- User Themes
- Alt Tab: Raise First Window
- Always Show Workspaces
- Desktop Icons NG (DING)
- Pop Shell
- Pop Shop Details
- System76 Power
- Ubuntu AppIndicators

**(10) Other Notes:**

System is fully updated

**Comment by jacobgkau** [comment]
Pop!_OS patches gnome-terminal to not snap its size to the nearest character, so the bug here is that creating multiple tabs reverts the snapping behavior. https://github.com/pop-os/gnome-terminal/issues/2 is related, but not exactly a duplicate.

I believe there's a way to ignore/override gnome-terminal's snapping (attempted in https://github.com/pop-os/shell/pull/498), but it came with too many other bugs to move forward with.

This issue should probably be transferred to https://github.com/pop-os/gnome-terminal unless there are any new ways to approach this from the Pop Shell side. (I wonder if the hint could only be ignored for certain windows/applications, but even if that was possible, it would require regression testing to make sure none of those other issues occur on affected windows.)

**Comment by ozdreamern** [comment]
Even patched, some wonky geometry bugs still show up with tabs in Terminal.  If I start with one terminal, and add a second tab, the terminal height shrinks by one row; if I close the tab, it shrinks by one row again.  (Repeating "ctl-shift-t" and "ctl-d" in succession, the terminal height will eventually shrink to a comically short window, and from then on it alternates between 3 rows and 2 rows high; it's pretty funny.)

Let me know if I should post a screencast.  I wasn't sure whether to create a new issue for this under gnome-terminal or add to this one.

**Comment by jacobgkau** [comment]
Fixed by https://github.com/pop-os/gnome-terminal/pull/9.
