### ISSUE TITLE
Please add back the activity view

### ISSUE THREAD

**Issue by rongcuid** [pop-os/shell#1162]
I am referring to the old Activity view in 20.04, the same one as vanilla Gnome 3, instead of Launcher, Workspace, or Application view in 21.04. I think this is necessary because #967 breaks the launcher for anyone who relies on IBus for inputting their language. I have investigated that bug, and it seems that something in Clutter/Pango is at fault, and there is probably nothing in Pop shell that can provide a fix. 

I propose bringing back the activity view, not just for working around this bug, but also to reduce confusion for those upgrading the system.

**Comment by mmstick** [comment]
Pop Shell is just a tiling window manager / launcher. The repository that controls this behavior is COSMIC, but I know that bringing the activity view back isn't an option, since that's an essential part of COSMIC. I'm sure there's something that can be done here to resolve the issue.

If you want to revert to having a normal GNOME experience, install gnome-session and select that at login.
