### ISSUE TITLE
Horizontal tiling doesn't split exactly in half.

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#117]
![Screenshot from 2020-03-26 16-58-50](https://user-images.githubusercontent.com/3430283/77705200-a9998c00-6f84-11ea-8f95-06e96bec9def.png)

**Comment by leviport** [comment]
I thought it might have been just gnome-terminal, but I can confirm that it happens with all applications. I think it may have something to do with the top bar, because I can resize it to get it almost perfect on a secondary display, as opposed to my primary, where I can't resize it to center at all (without mouse drags, at least).

![2020-03-27_08-03](https://user-images.githubusercontent.com/13512097/77764152-c7f19d00-7001-11ea-88a6-f2db0cac104c.png)

**Comment by isantop** [comment]
Are you guys sure it's not exactly in half? Try to align with e.g. a webam rather than the clock, since the clock is not necessarily in the exact middle of the panel.

**Comment by isantop** [comment]
I checked both of the screenshots posted here:

@WatchMkr Yours is split in the middle exactly, both the left column and the right column are the exact same width.

@leviport Yours are different, but it appears that may be due to the terminal not being able to resize to any arbitrary pixel size. It's limited to sizes which perfectly fit an integer-number of characters in width.

**Comment by leviport** [comment]
We're talking about horizontal halfness. Check out the red lines I doodled on my screenshot. They're supposed to show the height difference between two Nautilus windows.

**Comment by isantop** [comment]
Ah, yep. Just noticed that myself

**Comment by WatchMkr** [comment]
This is still happening for me.

```
pop-shell:
  Installed: 0.1.0~1585606052~20.04~8fb4de7
  Candidate: 0.1.0~1585606052~20.04~8fb4de7
  Version table:
 *** 0.1.0~1585606052~20.04~8fb4de7 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

![Screenshot from 2020-04-01 10-46-18](https://user-images.githubusercontent.com/3430283/78163798-1b029000-7406-11ea-882b-299a06c5f3f4.png)

**Comment by mmstick** [comment]
See if f40419d fixes it

**Comment by RrOoSsSsOo** [comment]
> See if f40419d fixes it

Works for me

**Comment by WatchMkr** [comment]
Looks good!
