### ISSUE TITLE
Launcher in the Workspaces View

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#1186]
Mockups: https://www.figma.com/file/6vzaICveLGHnUqZrZ8XVrn/Workspaces-search?node-id=116%3A480

![image](https://user-images.githubusercontent.com/3430283/133834103-d347f917-7706-48ef-aa62-563dacb7a3e9.png)
![image](https://user-images.githubusercontent.com/3430283/133834135-d6eb5f49-1d5f-40d3-90d3-c7e139304434.png)

**Comment by augt** [comment]
Adding this feature + being able to use horizontal workspaces with cosmic workspaces would be absolutely awesome. 

The default workspaces thumbnails in vanilla Gnome 40 are tiny and their background is black so it's difficult to distinguish the windows. 
The horizontal workspaces make it more intuitive to use 3 fingers swipe left/right gestures with touchpads on laptops to switch workspaces.
Plus being able to have just one single keyboard shortcut or swipe gesture (3 fingers up) to access either app launcher or workspaces view is also more intuitive in my opinion.

**Comment by ikeofkc** [comment]
This is a great mockup great work. +1 from one user here. Would anyone else be interested in a feature where drag-and-drop worked from the launcher to a workspace and/or to the dock? just a "nice-to-have" vs a necessity, but thought it would be worth mentioning since this has not yet been developed.

**Comment by WatchMkr** [comment]
Deferred to COSMIC DE
