### ISSUE TITLE
Older `Applications` menu can be opened with touchpad gestures 

### ISSUE THREAD

**Issue by helium18** [pop-os/shell#1277]
**(1) Issue/Bug Description:**
Gnome's `Applications` menu opens up when I swipe up twice with three fingers.
![](https://i.imgur.com/YRFPcvs.png)

**(2) Steps to reproduce (if you know):**
1. Install Pop!OS 21.10
2. Use the touch-pad to swipe up twice with three fingers. 

**(3) Expected behavior:**
Should be used for window navigation normally instead of opening up the menu. 

**(4) Distribution (run `cat /etc/os-release`):**

```NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
GNOME Shell 40.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```pop-shell:
  Installed: 1.1.0~1639174177~21.10~de901ae
  Candidate: 1.1.0~1639174177~21.10~de901ae
  Version table:
 *** 1.1.0~1639174177~21.10~de901ae 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Came preinstalled

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p (Horizontal)

**(9) Other Installed/Enabled Extensions:**
1. User Themes

Edit: Changed "Expected Behavior"

**Comment by leviport** [comment]
The defaults in 21.10 are set up so that three finger swipes in any direction change window focus, while a four finger swipe to the right opens the applications library. Can you test whether a four finger swipe to the right opens the app library?

If you wish to customize the defaults, the easiest way to do so is to install Touché from the Pop Shop and make changes there.

**Comment by helium118** [comment]
> Can you test whether a four finger swipe to the right opens the app library?

Yes it does open the app library when I do that.

I should update the expected Behavior to "Do nothing" since, like you've said, it should be used for changing the window focus... I face this only in Wayland and the three finger swipe works fine in X11.

> If you wish to customize the defaults, the easiest way to do so is to install Touché from the Pop Shop and make changes there.

Works flawlessly, thanks for the suggestion!
