### ISSUE TITLE
What is the status of upstreaming this to GNOME?

### ISSUE THREAD

**Issue by julben** [pop-os/shell#1356]
I do know that changing things GNOME is difficult and slow, even more with the current migration to GNOME 4x. But since I could not find information about this elsewhere, and it was mentioned in your `README.md`, I was wondering what was the status of upstreaming this set of features into GNOME.

**Comment by varac** [comment]
Same here - dear Pop Shell team, could you please give an update about the current state of Gnome integration ? I'd also like to know why the last release is so long ago (Jan 2021), any reasons that prevent a new release ?

**Comment by leviport** [comment]
I don't believe GNOME has any interest in having pop-shell upstreamed. If my assumption is wrong, then I'd love to hear about it.

> I'd also like to know why the last release is so long ago (Jan 2021), any reasons that prevent a new release ?

We don't regularly tag releases since tags are not necessary for updates in Pop!\_OS. If you want the most up-to-date pop-shell, you'll want to build it from `master`

**Comment by varac** [comment]
@leviport thanks for the summary, too bad :/

**Comment by jacobgkau** [comment]
I don't see why we can't tag a new release, it's not just not something that's always done regularly due to not being needed for the Pop!_OS development and release cycle. @mmstick Think you can tag a new release sometime soon?

(Tagging a release is unrelated to this issue, though, and indeed upstreaming an extension like this to GNOME is probably not something that GNOME would want.)

**Comment by mmstick** [comment]
There are some issues I'd like to have fixed before tagging a new release.

**Comment by julienbenjamin** [comment]
> I don't believe GNOME has any interest in having pop-shell upstreamed. If my assumption is wrong, then I'd love to hear about it.

Sorry the late answer.

As far as I am aware, the GNOME developers were interested but were not happy about the code quality at the time. I was not involved in this and discovered these talks a few months back. So, either there is a communication issue, or each side is blaming the other. I did not audit the code myself, so I'd not assume anything here. 

The only thing I know is that The GNOME Project has strict guidelines they expect every contributor to follow, and I might imagine how this would be a problem from your perspective. Anyway, please make sure of the information on the matter, because there seems to be a big discrepancy in discourse here.

**Comment by mmstick** [comment]
That would be the first I've heard of that. This is just an extension proving what is possible. Anything upstreamed would have been rewritten in Rust or C.

**Comment by jacobgkau** [comment]
> As far as I am aware, the GNOME developers were interested but were not happy about the code quality at the time. I was not involved in this and discovered these talks a few months back.

Do you have a source for this?

**Comment by IlChitarrista** [comment]
> That would be the first I've heard of that. This is just an extension proving what is possible. Anything upstreamed would have been rewritten in Rust or C.

@mmstick I couldn't find an issue about this on Gnome Shell, shouldn't someone open one to see the actual situation in a more systematic way?

I'm not a designer but I think that a well implemented automatic tiling system could bring a better overall UX to the table although I believe that there are some programs which are so simple that there should be a specific way for them to be handled without excessive resizing (Gnome Calculator for example is excluded by default on Pop!_OS but if this was to be implemented in the Shell itself it should be a more global setting stored somewhere  (I'm not well informed on this yet but perhaps there could be the possibility for this to be some sort of Freedesktop specification?)).

I'm not acquainted with the "drama" that supposedly happened between System76 and Gnome but I think that, especially with System76's great Rust engineers it would be a shame to miss an opportunity to improve the Linux Desktop overall.

**Comment by leviport** [comment]
Feel free to open a request on their Gitlab if you'd like, but it's not like they don't know about Pop Shell already. I'm thinking it's probably just not the direction their aiming for.

**Comment by IlChitarrista** [comment]
Maybe if we can show the UX benefits of Tiling there might be a chance to reconsider.

**Comment by leviport** [comment]
Like I said, feel free to open a request yourself, but I'm pretty sure I know what the answer will be. It's their prerogative, so your efforts will probably be better spent discussing it with them instead of us.

**Comment by IlChitarrista** [comment]
Sure, thanks for the advice, hopefully we can get this somewhere; if not Cosmic will be an even better choice. Happy Hacking Everyone :)
