### ISSUE TITLE
Wrong window focus when switching workspaces and in stacking mode

### ISSUE THREAD

**Issue by piotrc33** [pop-os/shell#1443]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
I have two workspaces
First of them has stacking mode with for example 3 applications A B C, last application opened is app C
I try to open app B from second workspace then I'm moved to proper workspace but still app C is visible
Then to open app B I have to pick it from bottom panel or somewhere else again and then it's focused correctly

**Steps to reproduce (if you know):**
Described above

**Expected behavior:**
When switching windows it should be focused immediately on correct one

**Comment by n3m0-22** [comment]
Steps to reproduce:

1. Open a windows on the first workspace
2. Setup a stack on the second
3. Go to the first workspace
4. Use `Super`+`Tab` or Launch to switch to a non focused window in the stack

Expected behavior:
Each action should move and focus to the window in the stack in the other workspace

Actual behavior:
The last window active in the stack remains showing but the one selected by either launcher or `Super`+`Tab` is active. 
- Nautilus is showing but I can right click and get a Virtualbox menu
- Nautilus is showing but I can type a command into the terminal

Example:

https://user-images.githubusercontent.com/11048214/169342569-2588ca61-8251-4b14-9ab2-66cbfe6e2952.mp4

**Comment by piotrc33** [comment]
@n3m0-22 Very nicely presented, thanks :)
