### ISSUE TITLE
Mouse jumping when clicking on dock item that's open on a different workspace

### ISSUE THREAD

**Issue by spacekookie** [pop-os/shell#1444]
I've noticed a strange bug on Pop_OS with the cosmic dock where clicking on an item in the dock, if the window is on a different workspace, will jump my mouse position to the top-left corner of the application that I selected. But not always?

Please let me know how I can give you further information about the version of the dock I'm running. I didn't see anything obvious in the settings

**Comment by jacobgkau** [comment]
pop-shell would be the extension moving the mouse cursor. I can recreate this when moving focus to an application on a different workspace using the dock. The cursor should never be moved as a result of clicking on anything, only as a result of using keyboard shortcuts.

**Comment by jmbuhr** [comment]
Is moving the mouse inherently coupled to focusing a window? I thought this would only be necessary if e.g. `focus on hover` were to be enabled. Maybe there could be an extra setting for this.
I use lots of keyboard shortcuts, but sometimes have to reach for the mouse. After working with this for a while now, I still find it breaking my flow when the mouse cursor is not where I last left it or when it jumps around while switching workspaces. It also breaks extensions like "Top Panel Workspace Scroll", because after one workspace switch the mouse will no longer be on the panel, so you can't scroll further to switch to the next.

**Comment by HeitorGabriel** [comment]
I have the same behavior in my Pop Cosmic. When moving through the workspaces, the mouse pointer jumps to top left-corner of the windows opened if the pointer not lays down over that windows.

**Comment by n3m0-22** [comment]
@HeitorGabriel The solution to this issue has been addressed. This should solve it for you https://github.com/pop-os/cosmic-workspaces/issues/76.
