### ISSUE TITLE
Shell allocates space in layout for minimized windows

### ISSUE THREAD

**Issue by isantop** [pop-os/shell#158]
When there are minimized windows, occasionally Pop Shell will allocate space for them in the layout, leading to empty spaces where there is no actual window visible, but where other windows can't expand into. Fixing this requires entering the overview to un-minimize the window, then re-minimizing it.

Screenshot showing the three windows currently open in the overview. The Nautilus window is minimized:

![Screenshot from 2020-04-14 13-53-12](https://user-images.githubusercontent.com/5883565/79268316-d04a3480-7e57-11ea-8135-39aa4d3fbee8.png)

Before entering the overview:

![Screenshot from 2020-04-14 13-53-06](https://user-images.githubusercontent.com/5883565/79268350-e22bd780-7e57-11ea-8be0-ecd5102d55e1.png)

**Comment by nicolae-stroncea** [comment]
Related bug(or same?):
1. Minimize window in workspace 1.
2. Drag minimized window from overview to workspace 2.
Result: Workspace 2 now has space allocated for minimized window, even though the window is still minimized

Another way:
1. Minimize window.
2. Restart shell.
Result: Broken layout.

In both of these cases, this can be fixed by un-minimizing the window before such actions, but i'm not sure if this would cover all cases where this bug occurs

**Comment by nicolae-stroncea** [comment]
Another case when this occurs is when you turn on `Tile Windows` option while an application is minimized.

**Comment by mmstick** [comment]
Is this and #159 now fixed?

**Comment by nicolae-stroncea** [comment]
Still allocates space if you set "Tile Windows" to ON while a window is minimized. This case can occur for many users, since the extension is off by default, and windows can have be in any possible state before extension is activated.

Also still occurs if shell is restarted while a window is minimized, but I imagine these 2 conditions being true at the same time will be quite rare for a regular user.

**Comment by mmstick** [comment]
Re-open if this is still an issue
