### ISSUE TITLE
Missing module `undici-types`

### ISSUE THREAD

**Issue by tarsobcaldas** [pop-os/shell#1664]
Hello, I'm using ArchLinux and I've been trying to install via both AUR and by trying to compile from the git repository. In both cases, when trying to compile, I get an error calling for a missing module `undici-types`, which I've tried installing, both locally and globally, resintalling typescript and other things, but haven't had any success.

**(1) Issue/Bug Description:**
When I try to compile
I multiple errors like
```
../../../../../node_modules/@types/node/globals.d.ts:344:37 - error TS2792: Cannot find module 'undici-types'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?

344         type RequestDuplex = import("undici-types").RequestDuplex;
```

All of them are in the same file, `globals.d.ts`.

**(2) Steps to reproduce (if you know):**

Trying to complie via any source

**(3) Expected behavior:**
Successful compilation

**(4) Distribution (run `cat /etc/os-release`):**
 Arch Linux

**(5) Gnome Shell version:**
Gnome Shell 45

**Comment by venkatmuthyala** [comment]
Recently got same error while building angular js application, Waiting for Solution :)

**Comment by vhespanha** [comment]
Waiting for solution too...

**Comment by clebsonsantos** [comment]
same error while building node application for rc-apps-engine. waiting for solution...

**Comment by vhespanha** [comment]
still get the same error

**Comment by Venryx** [comment]
I've encountered the same error; not with this "shell" repo, but in another context. But since this is the top google result for the error (and there is virtually no info on it), I figured I'd still post my solution here...

The only solution I've found so far is to downgrade `@types/node` from `20.10.6` to `20.0.0`. (forced the downgrade using yarn's "resolutions" feature: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions)

**Comment by ldm0** [comment]
Kind of weird, I fixed this error by deleting `node_modules` directory.

**Comment by tarsobcaldas** [comment]
> Kind of weird, I fixed this error by deleting `node_modules` directory.

Yup, that worked.

**Comment by akylbek04** [comment]
Thanks, it works

**Comment by lukepuplett** [comment]
> I've encountered the same error; not with this "shell" repo, but in another context. But since this is the top google result for the error (and there is virtually no info on it), I figured I'd still post my solution here...
> 
> The only solution I've found so far is to downgrade `@types/node` from `20.10.6` to `20.0.0`. (forced the downgrade using yarn's "resolutions" feature: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions)

For NPM users, add `"@types/node": "20.0.0"` to `devDependencies` and run `npm install`. Had this issue compiling my TS after updating some stuff to troubleshoot a different issue which was actually iCloud processes going nuts.

**Comment by riascho** [comment]
hi guys, 
what worked for me was to set `"moduleResolution": "node"` in the tsconfig

**Comment by borgboyone** [comment]
I just ran into this nasty issue after installing the selenium-webdriver and chrome-driver.  Adding "types": [], to my tsconfig.json file did remove the errors from my compilation step. However, I knew this didn't address the underlying issue. Taking a look at my "node_modules" directory under my project and snooping around revealed the root cause of the problem.  The fix explains it all.

Go into the "node_modules/@types" folder.  Look for "node/node_modules/undici-types".  Move the "undici-types" folder so that it is under"node_modules/@types".

That did the trick for me.
