### ISSUE TITLE
[AUR `-bin` package] Extension won't start on GNOME 45

### ISSUE THREAD

**Issue by taitep** [pop-os/shell#1678]
**(1) Issue/Bug Description:**
It gives an error in the Extensions app,, it looks like this:

The settings of extension pop-shell@system76.com had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///usr/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:1:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**(2) Steps to reproduce (if you know):**
Install.
Try to enable

**(3) Expected behavior:**
Able to enable pop shell

**(4) Distribution (run `cat /etc/os-release`):**
 Manjaro

**(5) Gnome Shell version:**
`GNOME Shell 45.1`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

`gnome-shell-extension-pop-shell-bin 1.2.0-4`

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1080p@60Hz

**(9) Other Installed/Enabled Extensions:**
Manjaro GNOME traditional layout defaults

**Comment by mmstick** [comment]
Which branch did you install?

**Comment by taitep** [comment]
I installed from the AUR.

**Comment by augustebaum** [comment]
Also hitting this error. GNOME shell 45.1, rev is [b5accce](https://github.com/pop-os/shell/tree/b5acccefcaa653791d25f70a22c0e04f1858d96e
) (from 2023-04-27). I'm on NixOS.

**Comment by mmstick** [comment]
@augustebaum Too old. You must install from the `master_mantic` branch.

**Comment by augustebaum** [comment]
> @augustebaum Too old. You must install from the master_mantic branch.

Okay I'll try it, thanks!

Although, I should note that it seems the AUR uses rev [aafc94](https://github.com/pop-os/shell.git#commit=aafc9458a47a68c396933c637de00421f5198a2a) from 2 weeks ago; so unless I missed something I would still expect the issue to occur after bumping my version.

**Comment by jacobgkau** [comment]
> Although, I should note that it seems the AUR uses rev [aafc94](https://github.com/pop-os/shell.git#commit=aafc9458a47a68c396933c637de00421f5198a2a) from 2 weeks ago; so unless I missed something I would still expect the issue to occur after bumping my version.

There are three packages in the AUR. OP said in his first post that he's using `gnome-shell-extension-pop-shell-bin`, which hasn't been updated since January 2021: https://aur.archlinux.org/cgit/aur.git/log/?h=gnome-shell-extension-pop-shell-bin 

The regular `gnome-shell-extension-pop-shell` package was last updated 11 days ago, but did switch to the correct branch back in October: https://aur.archlinux.org/cgit/aur.git/log/?h=gnome-shell-extension-pop-shell 

The `gnome-shell-extension-pop-shell-git` package pulls the latest commit, and also switched to the correct branch last month: https://aur.archlinux.org/cgit/aur.git/log/?h=gnome-shell-extension-pop-shell-git 

I'm going to go ahead and close this issue for now. @taitep Please try installing one of the latter packages, and/or building it yourself with `make local-install`, and let us know if you still have any issues. The `-bin` package was already marked out-of-date in the AUR this past January (11 months ago), so that package existing and being out-of-date needs to be handled in some way by the AUR contributors or maintainers.
