### ISSUE TITLE
Requesting update on 'Pop Shell on other Gnome desktops' article

### ISSUE THREAD

**Issue by syswraith** [pop-os/shell#1700]
https://support.system76.com/articles/pop-shell/

Can we add build instructions for using the Pop Shell on NixOS here?

**Comment by leviport** [comment]
That sounds like a great idea! The repo for those documents is https://github.com/system76/docs/, and that specific article can be found at https://github.com/system76/docs/blob/master/content/pop-shell.md

Since that repo is on the System76 org and not the pop-os org, I won't be able to transfer this issue to that repo, so I'll just close it for now. A new issue can be opened on the docs repo, if it's desirable to have a tracking issue. Although, if you're going to open a PR anyway, then an issue probably isn't necessary.
