### ISSUE TITLE
Display Changes Break the Tiling Layout

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#171]
Before adding a display
![before_adding_a_monitor](https://user-images.githubusercontent.com/3430283/79387292-a44ab400-7f28-11ea-8089-519f788e751d.png)
After adding a display
![after_adding_a_monitor](https://user-images.githubusercontent.com/3430283/79387317-b3c9fd00-7f28-11ea-8bde-b8ff86b595a0.png)

**Comment by LuxMiranda** [comment]
I'm having a similar issue where, when I disconnect from an external display, I have windows hanging off the edge of the screen in an often inaccessible way. I think it may be the same bug.

**Comment by benneti** [comment]
I also have the same issue as @LuxMiranda

**Comment by jacobgkau** [comment]
https://github.com/pop-os/shell/pull/721 should have helped with this. It was just released from proposed about 4 hours ago, so please install updates and see if the issue is still occurring (if it is, please provide the output of `apt policy pop-shell` to confirm you're running the latest version.)

**Comment by benneti** [comment]
I do not think it did, my version is 
```
pacman -Q gnome-shell-extension-pop-shell-git 
gnome-shell-extension-pop-shell-git r612.b962d4f-1
```
which should correspond to as of now latest https://github.com/pop-os/shell/commit/b962d4faa4ebf443e747122cc888edd78337878e commit.

To illustrate the current behaviour:
Initial window layout:
![Screenshot from 2020-11-26 10-05-44](https://user-images.githubusercontent.com/11725645/100330815-b49f3300-2fcf-11eb-8b3e-2c55e60bf4dc.png)
After disconnecting the the monitor (mind that the initial window on this screen becomes invisible and the window on the right is completely unusable)
![Screenshot from 2020-11-26 10-06-04](https://user-images.githubusercontent.com/11725645/100330837-bb2daa80-2fcf-11eb-9775-6e133b2f4634.png)
![Screenshot from 2020-11-26 10-06-10](https://user-images.githubusercontent.com/11725645/100330845-bd900480-2fcf-11eb-87ed-4ddcdeba6a93.png)

If I can provide you more information (without using apt) please let me now.

**Comment by benneti** [comment]
Seems to be much better on shell 1.2.0!
The only remaining problem is that disconnecting and connecting again does not restore the initial tiling but all windows are on the primary monitor.

**Comment by jacobgkau** [comment]
> The only remaining problem is that disconnecting and connecting again does not restore the initial tiling but all windows are on the primary monitor.

This is expected behavior; windows are supposed to stay where they are when connecting to a display. (I don't think we'd want windows always moving to a new display, e.g. for cases where you're plugging into a projector to share only certain windows; and I would imagine it would be a lot of work to reliably determine whether a display has been connected before, and to keep track of which windows were previously on a display that is not currently connected.)

**Comment by benneti** [comment]
That is what I suspected.
Still some logic when connecting another display to distribute the workspaces more evenly would still be nice.
Assuming that disconnecting a display moves the workspaces of the disconnected display to even workspaces of the (remaining) primary monitor.
So maybe you could consider adding an option for the inverse, i.e. connecting a monitor moves the even workspaces of the primary monitor to the newly connected one.
