### ISSUE TITLE
Half tiling in default floating mode does not work from keyboard shortcuts

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#180]
In the default window floating mode, half tiling windows with a keyboard shortcut does not work. In 19.10 this was done with Ctrl+Super+{left,right}.

Dragging windows with the mouse still works.

This is related to https://github.com/pop-os/shell/issues/36

**Comment by WatchMkr** [comment]
GNOME is considering changing workspaces from vertical to horizontal. There's a decent amount of support for this. We use Super + Control Up/Down for workspace. With that change, moving workspaces would be Super + Control Left / Right and mean we'd have to change this shortcut in six months or a year.

Because we have so many changes in 20.04, we're trying to get through the major-changes pain once and do it now. 

I don't have a good shortcut in mind. But I want to raise this issue for discussion.

**Comment by leviport** [comment]
I wonder if it's a shortcut that could exist only in window management mode, since changing workspaces isn't really something that is done in window management mode? So in WMmode, Super + Ctrl + up/down (later Super + Ctrl + left/right if it does change) snaps to half of the screen, and outside of WMmode, it changes workspaces normally. Or maybe Ctrl + Shift + directions since that one doesn't seem to do anything in WMmode, meaning the action falls through to the underlying window instead. Ctrl + directions and Shift + directions have actions in WMmode which prevents the actions falling through to the highlighted window.

I don't entering window management mode is what I find aggravating, but resizing and repositioning the window to half of the screen just requires so many keystrokes. It makes me more likely to just drag the window with my mouse instead, and I'd rather live on the keyboard as much as possible.

**Comment by brs17** [comment]
If GNOME is going to change the layout of workspaces, more redesigns/changes will need to be considered anyways since moving workspaces will need to be different as well. I think the priority here should be focusing on this regression and deal with any potential changes when and if they happen (I would have a number of questions about moving workspaces horizontally with external monitors set up horizontally as well).

**Comment by WatchMkr** [comment]
Yes, we need a shortcut to half tile. View split left/right as it's called.

I agree about multi-monitor and horizontal workspace issues. If GNOME moves forward with that design, I'm unsure we'll have a choice but to adopt.

I covered moving workspaces in the above comment. It's currently Super CTRL Up Down. Moving a window Super Shift Up/Down. Horizontal would change the Up/Down to Left/Right. That is a problem when workspace move left to right.

**Comment by WatchMkr** [comment]
> I wonder if it's a shortcut that could exist only in window management mode, since changing workspaces isn't really something that is done in window management mode?

Perhaps that's a solution. Super Enter then Super CTRL Left/Right. I worry about how different it is than the current shortcut.

@maria-komarova take a look at this one. Our current half tiling shortcut s disabled but we need a shortcut solution. You have the most insight into GNOME's design team plans.

**Comment by WatchMkr** [comment]
Clsoing to keep the GNOME plans private.

**Comment by brs17** [comment]
Conversation about GNOME plans can happen offline or elsewhere. This is still an issue though, so I think the issue should remain open.

**Comment by WatchMkr** [comment]
I will reopen a new issue.
