### ISSUE TITLE
Extending Launcher?

### ISSUE THREAD

**Issue by tinycrimsonpandas** [pop-os/shell#198]
Hey there!

I've been working with the shell all day, and I really think this project is excellent. Thank you very much for all of the hard work.

One of my favorite parts is the launcher, it's a really intuitive way to navigate between the different tiles and launch applications. I also spend a lot of time on Mac OS where I've used quicksilver and, most recently, Alfred. 

There are things that I wish it could do, like open a URL in the default browser. I don't know your design concept around the scope of the launcher, but it might be interesting to explore extensions to enable different actions in the launcher.

**Comment by AdamoPrincipe** [comment]
I use the Ulauncher for that.
https://ulauncher.io/

@tinycrimsonpandas maybe you can try that.

**Comment by dhollinger** [comment]
@AdamoPrincipe Ulauncher is great (I use it, too) but i'd rather not have two launchers running. So, either the ability to extend the Pop Shell Launcher or disable it entirely (in favor of something like uLauncher) would be great.

**Comment by mmstick** [comment]
Discussions on possible implementations are welcome

**Comment by tinycrimsonpandas** [comment]
I agree that I wouldn't really want to operate two different launchers.

Perhaps there are three options:

- Extend the pop_shell launcher to allow extensions
- Provide a few additional options in the Pop shell launcher (URLs, perhaps other depending on user testing)
- Create an extension for uLauncher that can controll pop_shell? Or even perhaps then even include uLauncher as part of pop_shell?

If I wanted to take a look at the launcher code as it exists today, where in the source can I find that?

**Comment by not7cd** [comment]
This file should interest you
https://github.com/pop-os/shell/blob/1d9c5b8d7e34763ce2f7b172ee879256e652488d/src/launcher.ts

I would like to create a custom mode, which would invoke a custom command.
Custom mode `g:$1` would run the custom command like `firefox -search "$1"`

**Comment by nicolae-stroncea** [comment]
@not7cd, @tinycrimsonpandas you can change the following things in src/launcher.ts:

### Make a google search by typing *gg* in pop shell launcher

1. Change the MODES variable to the following: `const MODES = [':', 't:', '=','gg'];`
2. Inside of apply method in launcher.ts, add this as the last if check:
```
 else if (id.startsWith('gg')) {
    const expr = id.slice(2).trim().toString();
    const query = 'https://www.google.com/search?q=' + expr.replace(/ /g, '+');
    const cmd = 'xdg-open ' + query;
    log.debug(cmd);
    spawnCommandLine(cmd);
}
```

### Launch a webpage by typing *url* from pop shell launcher

1. Change the MODES variable to the following: `const MODES = [':', 't:', '=','url'];`
2. Inside of apply method in launcher.ts, add this as the last if check:
```
else if (id.startsWith('url')){
    let url = id.slice(3).trim().toString();
    if(!(url.startsWith('https:') || url.startsWith('http:'))){
        url = 'https://'.concat(url);
    }
    const cmd = 'xdg-open ' + url;
    log.debug(cmd)
    spawnCommandLine(cmd)
}
```

If you want both changes, just add both sectios.


I would add this as a PR, but I'm not sure if @mmstick  would like extensions to be done directly inside of launcher.ts.

**Comment by WatchMkr** [comment]
The next step for us is working through UX interactions between the Activities overview and new Pop Shell functionality. As that work takes shape, the launcher features will come into focus.

A lot of these ideas are great and I suspect many will make it in. Keep them coming! We’ll take a careful and deliberate approach so the result is a cohesive experience throughout the desktop.

**Comment by anzanhoshin** [comment]
I use the Gnome launcher or Albert to open frequently used documents and
files. Without this, I find Pop Launcher pretty useless.


Anzan Hoshin roshi

**Comment by nicolae-stroncea** [comment]
I would also find a file search ordered by frequently used documents very useful. Since Ulauncher has some extensions for that, maybe they can be forked:
* https://github.com/dcervenkov/ulauncher-z-search - for opening frequently used files/folders
* https://github.com/brpaz/ulauncher-file-search - general file search, doesn't take frequency into account

**Comment by WatchMkr** [comment]
Adding comments from https://github.com/pop-os/shell/issues/257 to consolidate Launcher discussion.

> Issue/Bug Description:
> 
> I would like to hack around the PopOS launcher to integrate pass with it, much like I used with an albert extension.
> 
> However, looking at the source code for the launcher, while is does allow special syntax like :, :t > and =, it does not seem to be made customisable.
> 
> I could provide an extension as a PR to this repo but I bet you'd prefer to have those in dedicated repositories. Not everyone uses pass.
> 
> Steps to reproduce (if you know):
> 
> Expected behavior:
> 
> It should work like this:
> 
>     I open the launcher with <super> - /
>     I enter :pass in it, this directs the query to the pass extension we are talking about
>     The extension filters available passwords by fuzzy-matching whatever I put after :pass
>     On pressing enter on the desired entry, it is copied to my clipboard
> 
> Other Notes:
> 
> As the PopOS launcher is new and "bare" if I may say, it's probably worth looking at being compatible with extensions from popular launchers like Rofi or Albert. That would save everyone a lot of work.

**Comment by LouisKottmann** [comment]
I'd like to insist on the:

> As the PopOS launcher is new and "bare" if I may say, it's probably worth looking at being compatible with extensions from popular launchers like Rofi or Albert. That would save everyone a lot of work.

I'd even say: maybe it's preferable to just use one of the great launchers out there, unless Pop Launcher does something very specific?

**Comment by JordyScript** [comment]
Some great suggestions to extend the pop shell launcher. Could we get some feedback on what direction the team is considering? (e.g. allowing for user extensions? baking in the additional functionality outright? not doing anything beyond what launcher does now?) 

My own suggestion would be a knowledge management tool that queries a local key value store. 

What | How
-- | --
Get to clipboard | `need [Key]`
Save | `need [KeyWithoutSpaces] [Value]`
Delete | `need delete [Key]`
Open Storage file | `need open`
Reload Storage file | `need reload`

Inspiration taken from the [need plugin](http://www.wox.one/plugin/87) for Wox launcher

To implement the storage file, I would suggest TOML because it's easily human readable and it allows for multiline strings, which you could then insert through directly editing the storage file.

What do you guys think?

**Comment by JordyScript** [comment]
> I'd even say: maybe it's preferable to just use one of the great launchers out there, unless Pop Launcher does something very specific?

What the pop launcher does well is:
- it comes preinstalled on pop os
- it is well integrated with the pop shell and its tiling window manager
- launching apps
- running terminal commands
- being a calculator

The more (well suited) features it offers, the more it enhances the user experience.

**Comment by mmstick** [comment]
There will be support for custom scripts, plugins, etc. It's the next big area that I'm looking to improve now that the most glaring issues with stacking and tiling have been ironed out.

There will be some improvements to the way the current built-in features work, and some additional built-in features that are necessary for essential system functions. Basic things such as volume control, session control, opening a folder, recent documents, and running a local script.

Ulauncher is a great source of inspiration for how a launcher should ideally function, but the way that their plugins work are sadly not generic enough to port over to Pop Shell. Pop Shell will use a simple launcher API that uses IPC, so libraries won't be required to write plugins for it.

Scripts will declare their accepted prefixes and aliases. The launcher will choose a plugin to query if search box has a compatible query. The plugin will respond to tell the launcher about available options, and each option will have a name, description, icon, and ID. The launcher will pass back an ID if selected, and the plugin will be able to either give more options, give feedback for the entry, do nothing, or close the launcher. The IPC approach is ideal because plugins will need to dynamically update search results as the query is dynamically modified. That should cover virtually everyone's unique needs, and I'll try to make it as simple as possible to write plugins for.
