### ISSUE TITLE
Feature request: explicitly include or exclude applications from pop-shell

### ISSUE THREAD

**Issue by wmutschl** [pop-os/shell#232]
As I am having troubles with some applications with pop-shell (e.g. GitKraken) I was wondering whether there is a way to either explicitly include or explicitly exclude applications from pop shell?
My use case would be, that I love tiling for terminal and text editors, but would like to disable it for e.g. Gitkraken or Firefox.

**Comment by WatchMkr** [comment]
Thanks for your suggestion. Rather than excluding windows, we're working on a feature to address windows with minimal sizes too large to fit in the layout. It's being tracked here.

https://github.com/pop-os/shell/issues/85

Floating a window with `Super` + `G` is the suggested method to pull a window from the tiling layout.
