### ISSUE TITLE
Resizing shortcuts are different depending on window location

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#238]
Should be consistent regardless of location

                Shortcut::new(
                    "Increase Window Size",
                    Event::ResizeWindowIncrease,
                    Schema::Hardcoded(&["Shift", "→", "↓"]),
                ),
                Shortcut::new(
                    "Decrease Window Size",
                    Event::ResizeWindowDecrease,
                    Schema::Hardcoded(&["Shift", "←", "↑"]),

**Comment by taranjlu** [comment]
I'm wondering if it would be possible to have the window resizing be based on the direction that the user wants to move the window border (e.g. Shift + direction always resizes the window in that direction if possible). I understand why it can make sense to have a consistent hotkey that will always "increase/decrease" the size of the window, but it feels really unnatural to use say `Shift+Left` and then have the left border of the window move to the right in order to "decrease" the size.
