### ISSUE TITLE
Would be helpful to be able to navigate the launcher results with hjkl

### ISSUE THREAD

**Issue by taranjlu** [pop-os/shell#256]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
 ```
pop-shell:
  Installed: 0.1.0~1588274983~20.04~586efcc
  Candidate: 0.1.0~1588274983~20.04~586efcc
  Version table:
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Currently, when using the launcher it is not possible to use "hjkl" to navigate the results and the arrow keys must be used instead. It would be nice to be able to stay on home row while navigating the results. Some other application use Ctrl+hjkl to navigate results (I don't know if that conflicts with anything, but that would be my ideal keybinding).

**Comment by omrihar** [comment]
Or at least with `Ctrl+n` and `Ctrl+p`

**Comment by schiorean** [comment]
I wanted to create a new issue but I will add a comment in here since it's related with launcher navigation as well. If you think I better open a new issue please let me know and will do it.

Right after opening the launcher, in order to navigate the default results I have to use the arrow keys. This means I have to move my fingers over to another key (arrow keys). 

**Proposal**

I propose a similar behavior like the default Alt+Tab: When I open the launcher, say using the default Super+/ then cycle through the default results as long as I don't release the Super and start pressing the /. 
Reason: Many times I instinctively know what my open apps are and their position, so switching to an open app is much faster using a similar workflow as Alt+Tab. 

The ultimate goal is to ditch the Alt+Tab and use the only launcher to navigate open windows as well.

**Comment by jackpot51** [comment]
https://github.com/pop-os/shell/pull/252 looks like it takes care of this
