### ISSUE TITLE
Black screen on login after pop-shell update!

### ISSUE THREAD

**Issue by v-marinkov** [pop-os/shell#305]
As described here #277 after I updated and enabled `pop-shell` today, I get a black screen with a cursor after entering my password. Neither restart, nor reinstalling `pop-desktop` fixes this. My computer is unusable.

How can I fix this?

**Comment by v-marinkov** [comment]
Well, it turned out to be a classic case of something changing permissions in the home directory. So `sudo chown -R $(whoami):$(whoami) ~/` fixed it. But It's worth investigating why it happened.

Also, now `pop-shell` doesn't work. I enable it in Gnome Tweaks but nothing changes and after reboot it is again switched off.

**Comment by mmstick** [comment]
There may be other issues here causing this. The only update to Pop Shell since release has been the fullscreen fix, and that fix had zero risk of side effects.

**Comment by v-marinkov** [comment]
Can I reinstall `pop-shell` only or see logs of why it doesn't work?

**Comment by v-marinkov** [comment]
I will close this for now but anyone who encounters a similar issue in the future should reopen it to investigate the cause.

**Comment by benneti** [comment]
Hey I think I am hitting the same issue (on the master branch's latest commit https://github.com/pop-os/shell/commit/969e2c53d5259aa054d09aad633a77a501d774a7).

What happens is the following:
after rebuilding my nixos system (i.e. I should now have a well defined system state) if I try to log in to the x11 session I get a black screen cursor shows and nextcloud-client pops up (started via systemd after graphical target).
The problem is gnome-shell never starts up and I cannot switch to TTYs the only shortcut that works is Ctr+Alt+Delete to force a reboot.
When I first login to the wayland session (everything works as expected) and then in x11 it works there, too.
For this reason it might be that some dconf setting is setup incorrectly, but a dconf dump before and after wayland login show no difference.

This part of the journal might help (do I need one of pop-shell launcher folders?)
[log.txt](https://github.com/pop-os/shell/files/6356159/log.txt)

Is there a way I can find some more debug information?
