### ISSUE TITLE
Reassign Direction Keys

### ISSUE THREAD

**Issue by ljak** [pop-os/shell#311]
Hello pop-people !

As user of the [BÉPO keyboard layout](https://fr.wikipedia.org/wiki/B%C3%A9po) (dvorak-like layout, for French language) and VIM, I would like to be able to move the focus on windows with the keys C, T, S and R. However, it seems that these shortcuts are taking care off from the extension itself (as I did not find these entries inside Gnome Shortcuts).

Would it be possible to reassign the [direction keys](https://github.com/pop-os/shell#directional-keys) on other keys than H, J, K and L ?

Thanks and great work on this extension !

**Comment by mmstick** [comment]
You can reassign the shortcuts in Keyboard Settings in Pop!_OS. For other Linux distributions, you will have to modify the keys with gsettings

**Comment by UltraSalem** [comment]
Settings -> Keyboard shortcuts on Pop OS 20.04 does not contain the super-HJKL shortcuts, so they are not modifiable. For example, I have set "Lock screen" to Super+L in that settings page, yet Pop OS still treats that Super-L key combo as Super+Right Arrow and switches windows instead of locking my screen. I cannot find a "Keyboard Settings" in Pop OS, only "Keyboard shortcuts".

**Comment by de-abreu** [comment]
As a user of the Brazilian ABNT-2 Querty variant I would like to have movement using Super+jklç.
