### ISSUE TITLE
System Popups Shouldn't Tile

### ISSUE THREAD

**Issue by shaun-ba** [pop-os/shell#473]
I don't see why system notification popups for example a crash report dialog would be tiled.

Ubuntu 20.04

**Comment by laichiaheng** [comment]
They look like half of my screen is taken off by the small window.

**Comment by jmmaranan** [comment]
Can someone post a screenshot of what those system popups are?

**Comment by shaun-ba** [comment]
.

**Comment by mmstick** [comment]
Pop Shell already checks the WM type of every window when deciding between what should or shouldn't be tiled. So if there are any windows which are getting tiled, it's because they aren't properly defining themselves as dialogs or popups. The Dash to Dock panel in your screenshot, for example, is a floating window that never gets tiled because it declares itself as a dialog.

**Comment by shaun-ba** [comment]
.

**Comment by WatchMkr** [comment]
With tiling being new to the GNOME desktop, there are apps and corner-cases to work through. Some are scenarios we can improve in the Pop Shell extension. Others, like Apport error dialogs require an application patch.

Better tiling is underway in many GNOME apps thanks to new responsive design patterns being built in for mobile.
