### ISSUE TITLE
Remove Super+Enter binding (adjustment mode) on Arch linux

### ISSUE THREAD

**Issue by Giorgiofox** [pop-os/shell#535]
Hello, 
I've tried Pop Shell on Pop!_OS and it work very well. In gnome settings, is also possible remove some system keyboard bindings, like for example **super+enter** that enter in "**adjustment mode**". 
Installing this git on my Arch linux with Gnome (also on a fresh install) it's not possible to remove this binding. I realy need to user **super+enter** for another custom binding, how I can do that please?

**Comment by mmstick** [comment]
All shortcuts are controlled by gsettings values, so you can use gconf to change them.

**Comment by Giorgiofox** [comment]
Can you please point me of the correct values?
In /org/gnome/shell/extensions/pop-shell I can't found that setting and value. 
Or can you please point me to some documentation? 
thanks!

**Comment by bjornsnoen** [comment]
@Giorgiofox in case you're still looking, or if anyone gets here from google and reddit, the path is `/org/gnome/shell/extensions/pop-shell/tile-enter`, found it by cross-referencing some xmls in the repo. To disable it I've just set it to a shortcut I'm unlikely to use, couldn't figure out how to disable it outright.

`dconf write /org/gnome/shell/extensions/pop-shell/tile-enter "['<Super>?']"`
The reason you can't find them in the dconf-editor is because they apparently won't show  unless the default has been modified. Once you've edited the value you'll be able to find or modify it there.
