### ISSUE TITLE
Workspace management

### ISSUE THREAD

**Issue by RickDW** [pop-os/shell#549]
I've used i3 in the past, and one of the things I would love to see in the shell extension is having a separate workspace associated with each monitor. The only options in gnome are to cycle through workspaces on your primary screen while the other screens only get a single fixed workspace, or to make all screens share their workspace at all times. The first option makes secondary displays very static and inefficient, while workspaces are supposed to make things more efficient in my opinion. The second option is slightly better, but choosing this means you can't view multiple workspaces at the same time. 

I feel like this might be more of a gnome issue that can't be solved in the extension, but I'd be interested to hear your thoughts on this. I think it would make a lot of people happy.

**Comment by mmstick** [comment]
This is just a part of GNOME, and something an extension can't change

**Comment by c3n21** [comment]
PaperWM seems to have workarounded GNOME's limitations somehow.

https://github.com/paperwm/PaperWM

This could be a showcase video for "per monitor workspace" feature

https://www.youtube.com/watch?v=erfmz2DrFtU

I didn't test it myself since I'm already running on GNOME 40 and PaperWM haven't been updated yet
