### ISSUE TITLE
Keyboard shortcuts for moving window to workspaces up and down don't work.

### ISSUE THREAD

**Issue by PeytonHanel** [pop-os/shell#592]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

My keyboard shortcuts for moving window up and down to other workspaces doesn't work. I've tried changing them, but I think the last update I did in apt had patches for Pop Os and it broke the functionality.
![image](https://user-images.githubusercontent.com/26446761/94942775-97485f80-048b-11eb-9516-99919bf091d8.png)

**Steps to reproduce (if you know):**

Try using keyboard shortcuts to move window to  workspace up and workspace down.

**Comment by jacobgkau** [comment]
Thank you for the screenshot of your settings. If your custom shortcuts of `Shift-Alt-Down/Up` are not working, can you please search for "workspace", find the shortcuts called "Move to workspace above" and "Move to workspace below", set your custom shortcuts on those items, and see if that makes them start working? (There will also be "Move window one workspace down" and "Move window one workspace up," which should both be disabled.)

If that doesn't work, can you please provide the output of this command to show what version of pop-shell you have installed: `apt policy pop-shell`

Have you either rebooted or restarted GNOME Shell (Alt-F2, r, Enter) since you installed updates?

**Comment by PeytonHanel** [comment]
Yes I have restarted several times.
Here are my new shortcuts:
![image](https://user-images.githubusercontent.com/26446761/94975484-b7494480-04c6-11eb-96a3-626b0281b1c3.png)
I disabled the shortcuts I posted in my first post. Now I can move a window to the lower workspace, but I can't move a window to the upper workspace. I can move from workspace to workspace using super + up/down, but super+shift+up doesn't do anything, where as super+shift+down moves the window a workspace down

**Comment by jmmaranan** [comment]
@PeytonHanel - there is one more shortcut that was cut off in your screenshot. Should be `Move window one workspace up`.
Please try to rebind to that your `SUPER + SHIFT + UP`
![image](https://user-images.githubusercontent.com/348125/94975815-d9e85700-04e0-11eb-9dbe-031915e9f6e8.png)

**Comment by PeytonHanel** [comment]
Ah I see the mistake I made. Thank you for your help, all is good now.
