### ISSUE TITLE
[Feature proposal] Have same kind of floating exception but for shortcuts

### ISSUE THREAD

**Issue by bnjjj** [pop-os/shell#669]
Hello, before starting the implementation about this need I would like to suggest/discuss with you about a feature I would like to have. In fact I'm coming from several years on mac os and used a lot of shortcuts with cmd and arrow keys in my visual studio code. Today I'm facing several issues because these shortcuts are often linked to popos shell shortcuts. I already changed a lot of default shortcuts but there are some shortcuts I want to keep because it's very intuitive and I like it. 

So here is my proposal: maybe we could add a list of exceptions (for example: Visual Studio Code) to disable pop os shell shortcuts when I'm in this window. Maybe we can go further and choose which shortcuts we want to disable. I really try to improve my user experience but I don't want to have something very custom which fits only my needs, that's why I'm creating this issue, to find the best solution for everyone. 

Let me know you thoughts and thank you for all your work :) I really enjoy using it

**Comment by GaryBer** [comment]
None of the VS Code shortcuts use the Super key by default. I am assuming that you change them yourself to match OSX Style.

https://www.amazon.com/Design-Everyday-Things-Revised-Expanded/dp/0465050654

Disabling pop-shell shortcuts while on a specific application sounds painful for UX. Just flipping through windows using Super + Arrows may land you on a window that would disable you from moving to the next window.

I could think of a few ideas about the conflicting shortcut problem.

1. Add a keyboard shortcut editor directly on pop-shell so that they shortcuts would be easier to modify. Would be better than going in the OS to change a shortcut or editing a config file.
2. If you do focus on a window that disables pop-shell shortcuts it would be best to have an escape to re-enable them by hitting the Super key 2 times really quickly or something along those lines. 
3. If you are on an application that you would want to disable shortcuts on it may be better to append another key to the shortcut for pop-shell. Go from [Super + B] to [Shift + Super + B].
4. If you are on a window that disables pop-shell shortcuts then change the active hint color to something that stands out. Provide a visual queue that something is out of the ordinary.

**Comment by bnjjj** [comment]
Yes indeed I kept my OS X shortcuts. But you're right about bad UX, especially when you're moving from window to window. I didn't think about that. Hmmm thanks for your ideas ! Maybe we could imagine a kind of threshold ? Like if you're focus on this window more than 10secs then disable shortcuts ? And use your idea with enable key to re enable shortcuts ?

**Comment by GaryBer** [comment]
The threshold idea is better, but it would end up confusing people like me.  It falls into the realm of `unexpected` behavior. 

Personally, I am leaning towards a the toggle via a shortcut idea. While in the `disabled shortcuts mode`, change the active hint border color to a `disabled hint color`. 

This is a very difficult UX design problem that may be solved by taking a few showers :D

**Comment by mmstick** [comment]
In GNOME, the Super key is exclusively for OS shortcuts, so you should expect there to be conflicts when using them.
