### ISSUE TITLE
Applications with large minimum size are displayed over other tiled apps if they don't fit

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#81]
**Steps to reproduce**:

1. Open up browser.
2. Open up 2 terminals on the right side of screen (vertically tiled on one another).
3. Focus on top right terminal.
4. Launch Gnome Calendar. Calendar will try to tile itself by top right terminal. Because its too large, it lays on top of other tiled applications. Additionally part of it will be hidden outside of the screen.

![broken_behaviour](https://user-images.githubusercontent.com/39338488/76790022-683efa80-6794-11ea-9afc-7d9aea8ae353.png)

**Intended behaviour**:

Calendar should find a better way to tile itself *properly*. In this case, the calendar fits best under the browser, or if it's stacked horizontally over/under the 2 terminals. I think cases like these can possibly occur in a lot of different window layouts where there is little real estate  available on the screen. A possible solution is if apps don't find enough space for themselves on the screen, they could launch in floating mode, and let the user have control over where to place it. Disadvantage might be that it wouldn't be **true** auto-tiling mode.

Some images of what good placement:

![intended_behaviour_1](https://user-images.githubusercontent.com/39338488/76790031-6c6b1800-6794-11ea-8fbc-383315c91cb6.png)
![intended_behaviour_2](https://user-images.githubusercontent.com/39338488/76790032-6d9c4500-6794-11ea-8ce2-cab6ee0b16aa.png)

*Frequency*: I've encountered this issue pretty frequently over the last 2 days with multiple applications: Calendar, Geary, VSCode.

**Comment by WatchMkr** [comment]
Thanks for your report. Many applications will require updates to make them work well in smaller spaces. Fortunately, a lot of this is already happening in the Linux community to support scaling down to phone screen sizes. It'll take time and some applications may never get there. We've been developing work-arounds for those instances.

From a UX perspective, where an application appears when launched needs to remain consistent. We therefore will only launch a window in relation to the window that currently has focus. Otherwise, auto tiling will become inconsistent leading to confusion about what might happen when an application is launched.

**Comment by mmstick** [comment]
What's going to happen when I've completed it is that windows and forks will adjust to compensate for the minimum size of a newly-created or moved window. At least to the best that we can compensate.

So in the first screenshot, the idea will be to shrink its adjacent window to the left and move the calendar sibling to the left so that it fits on screen, and then it will increase the ratio of its parent fork adjacent to to the window sibling beneath the fork.

If the window sets a WM_SIZE_HINT with base values indicating that it tiles better vertically, we may be able to use that information to favor vertical tiling.

**Comment by mmstick** [comment]
Merging with #85
