### ISSUE TITLE
Move Windows Left

### ISSUE THREAD

**Issue by e2dubba** [pop-os/shell#870]
**(1) Issue/Bug Description:**
With `Super+Shift+L` i can move the windows right, but with `Super+Shift+H`, I cannot move windows Left. I pulled the latest shell, and rebuilt from sources. (the arrow keys do not work either)
I can switch windows with `Super+H`, but not move the window. 

**(2) Steps to reproduce (if you know):**
I rebuilt from the latest master branch, and it wasn't working 

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**(5) Gnome Shell version:**
3.36.8 (running wayland) 

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

I am running this on vanilla ubuntu. :-D

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2 external 1080p (horizontal)
1 internal 4k monitor

**(9) Other Installed/Enabled Extensions:**
Powered through an Ankr Thunderbolt dock 

**(10) Other Notes:**

**Comment by bflanagin** [comment]
@e2dubba thanks for reporting the issue. For clarification are you trying to move the windows to another screen/workspace or are you wanting to move them around the current screen? I see you have multiple monitors and wanted to be sure I test it correctly.

**Comment by e2dubba** [comment]
Thank you for asking the clarifying question. I want to move it to a different screen. (I can move them to the screen to the right, but not to the left). I can move it between vertical workspaces.

**Comment by bflanagin** [comment]
Hmm, the bug isn't happening on my system. It might require multiple external monitors so I'll pass it to someone that can test it further.

What I tested

Monitor on the left:

* super+shift+h/l
* super+shift+numpad 4/6
* super+shift+arrow left/right

Monitor on the right:

* super+shift+h/l
* super+shift+numpad 4/6
* super+shift+arrow left/right

**Comment by e2dubba** [comment]
Thank you for looking into this. And I knew this bug was going to be really obnoxious to try and reproduce.

**Comment by jacobgkau** [comment]
```
(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):
2 external 1080p (horizontal)
1 internal 4k monitor
```

When using this layout with two 1080p displays on either side of a 4k display:

![Screenshot from 2021-02-05 15-54-18](https://user-images.githubusercontent.com/7199422/107097614-9ec99d80-67ca-11eb-9553-14aa1d5ea798.jpg)

The only problem I'm having is that if I try to move leftward from the right-most display, the window moves all the way to the left-most display, skipping the center display. (I'm seeing this with a variety of other resolution combinations in the same horizontal layout.)

@e2dubba Can you please provide a screenshot of your display settings, so we can see the exact shape/layout you have your displays arranged in? Does the same issue occur if you log in with Xorg instead of Wayland?

It may be worth running these commands in the shell directory to re-configure the keyboard shortcuts, in case it's a configuration issue:

```
rm .confirm_shortcut_change
make configure
```

**Comment by e2dubba** [comment]
Okay, i ran the commands, and still have the same issue. 



![Screenshot from 2021-02-05 16-11-18](https://user-images.githubusercontent.com/16321747/107098986-76f92a80-6808-11eb-929a-f8be28b11f09.jpg)

**Comment by e2dubba** [comment]
The 4K screen is on the farthest left, and the two 2k monitors are to the right.

**Comment by e2dubba** [comment]
I also confirmed that the issue is still occurring with X.

**Comment by parrotcar00** [comment]
I can confirm that I'm seeing this bug as well. My setup is a laptop with a single external monitor.

My laptop is my primary display and the external monitor serves to extend that workspace.

I can move windows to the right (from my laptop to my external monitor) but cannot move them back.

So, ```Super + Shift + Left Arrow``` is not working but ```Super + Shift + Right Arrow``` works.

My pop-os shell version is the latest master commit:

```commit 395671e81561d3d6076631120c7a6ae032222933 (HEAD -> master, origin/master, origin/HEAD)
Author: Mike Wallio <michael.wallio@outlook.com>
Date:   Tue Mar 2 00:24:55 2021 -0500

    feat(plugin-web): Match sites via a map; Add Flathub, GitHub Gists, and NPM

````

**Comment by gregorriegler** [comment]
I do have the same Issue.

Ubuntu 20.04.2 LTS.

Two Monitors.
Primary (left side) 1920x1200.
Secondary (right side) 1920x1080.

I can move around everything around with but one exception:
If the primary screen is empty (no windows), and I have a window on the second screen, I cannot move the window to the left screen with Super + Shift + Left as expected.
Strangely, I am able to move the Window to the left screen by using Super + Shift + Up or Down as a workaround

**Comment by ningvin** [comment]
I am also experiencing the same issue since upgrading to Pop!_OS 21.04.

My setup:
- left side: 3840 x 2160
- right side: 2560 x 1440

If the bigger screen on the left is set as the primary monitor, I can only move windows from the left to the right screen using `Super + Shift + Right`, but not from the right to the left. `Super + Shift + Left` has no effect.

If instead the smaller screen on the right is set as the primary monitor, I can move windows between my screens just fine using `Super + Shift + Left` and `Super + Shift + Right`.

Strangely, in both case I can move windows from the primary screen to the secondary screen by pressing `Super + Ctrl + Shift + Up` and from the secondary screen to the primary screen by pressing `Super + Ctrl + Shift + Down`. These shortcuts should move the windows to the upper and lower monitor respectively.

Enabling or disabling fractional scaling does not have any effect on this behavior.

**Comment by darkroom2** [comment]
I am also facing this issue. Are there any workarounds or plans for fixing? Thanks.
