### ISSUE TITLE
Feature Request : Support persistence of tiling applications

### ISSUE THREAD

**Issue by kaushalyap** [pop-os/shell#872]
First thanks for the awesome extension. I have a feature request to make this extension more awesome.

Usually we open several applications and tile them according to our preference after every reboot. ex: Web browser on one monitor, text editor and terminal open in another monitor.

I would be great if this extension have ability to remember where a particular application window was tiled previously. So the next time we launch that application again it will be tiled where it was tiled previously.

Possible approaches:

1. Extension remembering(snapshot) applications last tiled positions automatically.
2. Allowing user to configure application tile position in settings.

I suppose first approach is a good start which will help to implement it in settings later by allowing user to customize the automatically remembered tiling.

**Comment by PeSader** [comment]
Duplicate of [#735](https://github.com/pop-os/shell/issues/735) and related to [#413](https://github.com/pop-os/shell/issues/413).

In any case, I've been using a combination of the [Auto Move Windows](https://extensions.gnome.org/extension/16/auto-move-windows/) extension with [LWSM](https://github.com/johannesjo/linux-window-session-manager) and a fixed number of workspaces (instead of dynamic ones) to get achieve more or less what you're looking for. The apps per workspace are restored successfully, but not the layouts unfortunately.

Maybe looking into LWSM may help finding an approach to implement this.

**Comment by kaushalyap** [comment]
@PeSader thanks for the info.

I'll close this since it is duplicate.
