### ISSUE TITLE
[feature] make stacking optional

### ISSUE THREAD

**Issue by jbytes1027** [pop-os/shell#878]
add an option to disable stacking/tabbed windows - I personally don't use the feature and it makes rearranging windows via dragging slower/more tricky

**Comment by WatchMkr** [comment]
Improving intent and better displaying the potential result in the overlay, such as showing tabs in the overlay when the window will tab, is preferable to a disable option.

**Comment by Quelklef** [comment]
Improved feedback would be nice, but a disable option would be super useful as well, IMO.

I just installed a Pop!_OS update which, I suppose, included a patch to the shell. Before this patch, tiling with the mouse would only change window position and sizing. Now, it also stacks. I *never* want to stack, so it only gets in my way. It has been very frustrating for me.

I can of course learn to live with this new behaviour, but it seems to me that making this optional shouldn't be a huge ask. Please correct me if I am wrong.

As a side note, Pop!_OS is otherwise f*cking awesome. I don't think I've had any other issues with it, and I've never been happier with an OS.

**Comment by mmstick** [comment]
Stacking is a core feature and I'd rather we not have dozens of toggles to disable every feature we implement. Improving the recognition of intent is much more reasonable.

**Comment by sgtsquiggs** [comment]
I accidentally stack all the time. It is very obnoxious but did not happen previously. Not sure when this started.
